//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webbanhang.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Product
    {
        public int Id { get; set; }
        [Display(Name = "Tên Sản Phẩm")]
        public string Name { get; set; }
        [Display(Name = "Hình Ảnh")]
        public string Avatar { get; set; }
        [Display(Name = "Danh Mục")]
        public Nullable<int> Categoryid { get; set; }
        [Display(Name = "Mô Tả Ngắn")]
        public string ShortDes { get; set; }
        [Display(Name = "Mô Tả")]
        public string FullDescription { get; set; }
        [Display(Name = "Giá Sản Phẩm")]
        public Nullable<double> Price { get; set; }
        [Display(Name = "Giá Khuyến Mãi")]
        public Nullable<double> PriceDiscount { get; set; }
        [Display(Name = "loại")]
        public Nullable<int> Typeid { get; set; }
        [Display(Name = "Thương Hiệu")]
        public string Slug { get; set; }
        public Nullable<int> Brandid { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> ShowOnHomePage { get; set; }
        public Nullable<int> DisplayOder { get; set; }
        public Nullable<System.DateTime> CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> UpdateOnUtc { get; set; }
        [NotMapped]
        public System.Web.HttpPostedFileBase ImageUpLoat { get; set; }

    }
}
